# Generated by Django 5.2.8 on 2026-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="discount",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
